# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: red

# SEO
marketing:
  seo:
    site_type: EducationalOrganization
    local_business_type: ''
    org_name: 'UWASIC'
    description: 'UWASIC is a student design team at the University of Waterloo dedicated to exploring the world of ASIC and FPGA development.'
    #    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text:
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Join Us"
      url: "#join-us"
    show_search: false
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} UWASIC'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
